### PR TITLE
New Character Set (HKSCS)

### PR DESCRIPTION
**Pull request by hkben**
Support HKSCS
Modify some flow to adapt new Character Set

### CODE REVIEW

**Comment by hkben** [comment]
The character set is converted by hand. May have made some mistakes. I need some time to test it.

**Comment by tobychui** [comment]
Sure, I will wait until your confirmation on the accuracy of the character set. Let me know when you are ready to merge :)

**Comment by hkben** [comment]
I think it's ready to merge.

**Comment by tobychui** [comment]
Thanks for the notification. I will check it out by tonight.

**Comment by tobychui** [comment]
I have discovered some minor issue while reviewing the code as follow.


The place where it should have no words was shown as * (which is normal). However, for those words that is inside HKSCS, it is not shown and it was shown as a blank grid instead. 
I guess this might be my system's  problem, do you got any screenshot of it working on your machine?
Many thanks.

**Comment by hkben** [comment]
I am using Win7 and 新細明體 . Maybe a font problem?

hkscs

I have some words are missing too. 
hkscs2

**Comment by tobychui** [comment]
> 
> 
> I am using Win7 and 新細明體 . Maybe a font problem?
> 
> hkscs
> 
> I have some words are missing too.
> hkscs2

Thanks, I will check if changing to 新細明體 will help. If yes, all the versions later on will force to use font 新細明體 .

**Comment by tobychui** [comment]
Tested with font "MingLiU_HKSCS". Working perfectly without problem. "MingLiU_HKSCS" will be used as the default font since next version (This font has been included in Windows since Vista)
test

**Pull request merged**
