### PR TITLE
Last Name Mode

### PR DESCRIPTION
**Pull request by hkben**
Add Last Name Mode in cyinput and simplify the flow to avoid WET code and easy for maintenance .

Please let me know if there are any bugs or problems.

### CODE REVIEW

**Comment by hkben** [comment]
And I think we can support multi page associate Mode with this flow now

**Comment by tobychui** [comment]
Hi Ben, thanks for the pull request. It seems you have been updating a large portion of the code logic involving the charcode phrasing logic. I will need a bit more time to review your code. Thanks.

**Comment by tobychui** [comment]
> 
> 
> And I think we can support multi page associate Mode with this flow now

The current data set do not have enough associate chars to support multiple page associate mode. I guess if you have the time to work on this project, may I ask if you can help with tidying up the homo-phonic data set first? It is currently unsorted and kind of difficult to use.

**Comment by hkben** [comment]
> 
> 
> > And I think we can support multi page associate Mode with this flow now
> 
> The current data set do not have enough associate chars to support multiple page associate mode. I guess if you have the time to work on this project, may I ask if you can help with tidying up the homo-phonic data set first? It is currently unsorted and kind of difficult to use.

I mentioned that because I already had a new associate chars from android version which needed for multi page support and is ready to use. (This is well-formed , unlike others , so I can convert it within a minute)

I haven't checked the homo-phonic flow yet , will see what can I improve.

**Comment by tobychui** [comment]
Issue found on LargeUI 選字 Mode. 
UI element cannot enter word selection mode. Please check if there are any logic error involved in largeUI background rendering. Thanks.

**Comment by hkben** [comment]
> 
> 
> Issue found on LargeUI 選字 Mode.
> UI element cannot enter word selection mode. Please check if there are any logic error involved in largeUI background rendering. Thanks.

Oh! I forgot the flow in largeUI also need to change. Just change the flow very quick. The problem seems to be fixed. Please let me know if there are any other problems.

**Comment by tobychui** [comment]
Thanks! I will do another code review tonight,

**Comment by tobychui** [comment]
Code reviewed. Seems there is issue entering 姓氏 Mode. 
I guess there is some critical bug in the logic of the charcode parsing. Please recheck the logic flow if possible and see if the bug still exists.
Illustrate with the image below.

**Comment by hkben** [comment]
I cannot reproduce this bug.

> 
> 
> Code reviewed. Seems there is issue entering 姓氏 Mode.
> I guess there is some critical bug in the logic of the charcode parsing. Please recheck the logic flow if possible and see if the bug still exists.
> Illustrate with the image below.
> 
> 

I cannot reproduce this bug, but I thought I met similar situation before. Try to make some changes in mapped_char and save it. I believe VS is caching some resources.

**Comment by tobychui** [comment]
> 
> 
> I cannot reproduce this bug.
> 
> > Code reviewed. Seems there is issue entering 姓氏 Mode.
> > I guess there is some critical bug in the logic of the charcode parsing. Please recheck the logic flow if possible and see if the bug still exists.
> > Illustrate with the image below.
> > 
> 
> I cannot reproduce this bug, but I thought I met similar situation before. Try to make some changes in mapped_char and save it. I believe VS is caching some resources.

Sure, I will rebuild the whole project and test again tonight.

**Pull request merged**
